"""
Generate semantic categories for all 2048 BIP-39 words.
Used by the smart twenty-questions attacker to narrow candidates.

Categories are designed to split the wordlist roughly evenly
and be answerable by small language models (semantic/conceptual,
NOT counting or spelling).

Run: python categorize_bip39.py
Output: bip39_categories.json
"""

import json

# Load wordlist
with open("bip39_wordlist.txt") as f:
    words = [w.strip() for w in f if w.strip()]

assert len(words) == 2048, f"Expected 2048 words, got {len(words)}"

# ============================================================
# CATEGORY DEFINITIONS
# Each word gets tagged with ALL categories that apply.
# Questions are designed around these tags.
# ============================================================

# --- CONCRETE vs ABSTRACT ---
ANIMALS = {
    "ant", "bacon", "bear", "bird", "buffalo", "butterfly", "canoe", "cat",
    "cattle", "chicken", "claw", "coyote", "cricket", "crouch", "deer",
    "dinosaur", "dog", "dolphin", "donkey", "dove", "duck", "eagle",
    "egg", "elephant", "fish", "flock", "fly", "fox", "frog", "giraffe",
    "goat", "goose", "gorilla", "hamster", "hawk", "hen", "horse",
    "insect", "jaguar", "jellyfish", "kangaroo", "kitten", "leopard",
    "lion", "lizard", "lobster", "mammal", "monkey", "monster",
    "mosquito", "mouse", "mule", "nest", "ostrich", "oyster", "panda",
    "panther", "parrot", "pelican", "pet", "pig", "pigeon", "pony",
    "puppy", "rabbit", "raccoon", "raven", "salmon", "scorpion",
    "shrimp", "snake", "spider", "squirrel", "swan", "tiger",
    "tortoise", "tuna", "turkey", "turtle", "weasel", "whale", "wing",
    "wolf", "zebra",
}

NATURE_PLANTS = {
    "apple", "avocado", "bamboo", "banana", "bean", "blossom", "broccoli",
    "cabbage", "cactus", "celery", "cherry", "coconut", "corn", "cotton",
    "farm", "field", "flower", "forest", "fruit", "garden", "garlic",
    "ginger", "grain", "grape", "grass", "harvest", "jungle", "lawn",
    "leaf", "lemon", "mango", "maple", "meadow", "mushroom", "oak",
    "olive", "onion", "orange", "orchard", "palm", "peanut", "pear",
    "pepper", "potato", "pumpkin", "rice", "rose", "salad", "seed",
    "spring", "stem", "tomato", "tree", "walnut", "wheat", "wood",
}

BODY_PARTS = {
    "ankle", "arm", "blood", "bone", "brain", "chest", "chin", "ear",
    "elbow", "eye", "eyebrow", "face", "finger", "foot", "hair", "hand",
    "head", "heart", "hip", "jaw", "knee", "leg", "limb", "lip",
    "muscle", "neck", "nerve", "nose", "organ", "pulse", "rib",
    "shoulder", "skeleton", "skin", "skull", "stomach", "thumb", "toe",
    "tongue", "tooth", "waist", "wrist",
}

TOOLS_OBJECTS = {
    "anchor", "armor", "arrow", "axe", "badge", "bag", "ball", "banner",
    "bar", "barrel", "basket", "belt", "bench", "blade", "blanket",
    "board", "bomb", "book", "bottle", "box", "bracket", "brick",
    "bridge", "broom", "brush", "bucket", "bullet", "bunker", "cable",
    "cage", "camera", "can", "candle", "cannon", "canvas", "car",
    "card", "carpet", "cart", "case", "castle", "ceiling", "cement",
    "chain", "chair", "chalk", "cigar", "circle", "clay", "click",
    "clip", "clock", "cloth", "club", "clutch", "coach", "code", "coil",
    "coin", "column", "couch", "cradle", "crane", "cup", "cupboard",
    "curtain", "cushion", "cycle", "desk", "device", "diagram", "dial",
    "diamond", "diary", "dice", "dish", "doll", "door", "dose", "dress",
    "drill", "drum", "dust", "elevator", "engine", "envelope", "fabric",
    "fan", "fence", "file", "film", "filter", "flag", "flame", "flash",
    "flat", "flip", "float", "floor", "foam", "foil", "fold", "fork",
    "frame", "fuel", "furnace", "furniture", "gadget", "garage", "gas",
    "gate", "gauge", "gift", "glass", "globe", "glove", "glue", "gold",
    "grid", "guitar", "gun", "gym", "half", "hammer", "hat", "helmet",
    "hint", "hockey", "hole", "hood", "horn", "hub", "ice", "image",
    "inch", "iron", "item", "ivory", "jacket", "jar", "jeans", "jewel",
    "junk", "key", "kitchen", "kit", "kite", "knife", "lab", "label",
    "ladder", "lamp", "laptop", "layer", "lens", "letter", "library",
    "license", "lift", "light", "limousine", "link", "list", "load",
    "loan", "lobster", "lock", "loop", "luggage", "lumber", "machine",
    "magnet", "mail", "mansion", "manual", "marble", "mask", "mat",
    "match", "material", "matrix", "maze", "mechanic", "medal", "menu",
    "mesh", "message", "metal", "method", "milk", "mirror", "mobile",
    "model", "monitor", "motor", "muffin", "museum", "net", "network",
    "note", "nut", "object", "office", "oil", "oven", "oxygen", "paddle",
    "page", "pair", "palace", "panel", "paper", "patch", "path",
    "pattern", "payment", "pen", "penalty", "pencil", "phone", "photo",
    "phrase", "piano", "picture", "piece", "pill", "pillow", "pin",
    "pipe", "pistol", "pizza", "place", "plastic", "plate", "pledge",
    "plug", "plunge", "poem", "pole", "pool", "pottery", "powder",
    "print", "prison", "prize", "program", "property", "proof",
    "protect", "pudding", "pull", "pulp", "pump", "punch", "purse",
    "push", "puzzle", "pyramid", "rack", "radar", "radio", "rail",
    "ramp", "razor", "recipe", "record", "ribbon", "ride", "rifle",
    "ring", "road", "robot", "rocket", "roof", "room", "rope", "route",
    "rubber", "rug", "rule", "runway", "saddle", "sail", "salon", "salt",
    "sample", "sand", "sauce", "sausage", "scale", "scene", "scissors",
    "screen", "script", "sea", "seat", "section", "setup", "shadow",
    "shaft", "shed", "shell", "shield", "ship", "shoe", "shop", "sign",
    "silk", "silver", "siren", "skate", "sketch", "ski", "skirt", "slab",
    "slam", "slice", "slide", "slot", "soap", "sock", "soda", "soldier",
    "solution", "song", "soup", "source", "space", "spare", "spice",
    "spike", "spin", "spirit", "spoon", "sport", "spot", "spray",
    "stadium", "staff", "stage", "stairs", "stamp", "stand", "state",
    "station", "steak", "steel", "step", "stereo", "stick", "stock",
    "stone", "stool", "stove", "street", "stuff", "style", "suit",
    "supply", "surface", "surge", "symbol", "syrup", "system", "table",
    "tackle", "tag", "tail", "tank", "tape", "target", "task", "tattoo",
    "taxi", "tent", "test", "text", "theme", "ticket", "timber", "title",
    "toast", "tobacco", "token", "tool", "top", "torch", "toss", "tower",
    "toy", "track", "train", "trap", "trash", "tray", "treat",
    "trigger", "trim", "trip", "trophy", "truck", "trumpet", "trust",
    "tube", "tunnel", "umbrella", "uniform", "unit", "update", "upgrade",
    "usage", "utility", "vacuum", "valve", "van", "vanish", "vapor",
    "vault", "vehicle", "velvet", "vendor", "venture", "venue", "verb",
    "version", "vessel", "video", "vintage", "violin", "virtual",
    "virus", "visa", "void", "volcano", "volume", "vote", "voyage",
    "wage", "wagon", "wall", "warfare", "warrior", "wash", "wasp",
    "waste", "water", "wave", "weapon", "web", "wedding", "wheel",
    "whip", "whisper", "width", "window", "wine", "wire", "wood", "wool",
    "word", "work", "world", "wrap", "wreck", "wrestle", "write",
    "yard", "zone",
}

SPACE_ASTRONOMY = {
    "alien", "asteroid", "atom", "comet", "cosmos", "eclipse", "galaxy",
    "gravity", "lunar", "moon", "north", "orbit", "planet", "polar",
    "rocket", "satellite", "solar", "south", "space", "sphere", "star",
    "sun", "sunny", "sunset", "universe", "void",
}

WEATHER_ELEMENTS = {
    "air", "arctic", "autumn", "beach", "blizzard", "breeze", "bright",
    "climate", "cloud", "cold", "cool", "dawn", "day", "draft", "dry",
    "dust", "earth", "east", "fire", "flame", "flash", "flood", "flow",
    "flush", "foam", "fog", "frost", "frozen", "glow", "heat", "ice",
    "lava", "light", "lightning", "melt", "mist", "moon", "morning",
    "night", "ocean", "ozone", "rain", "river", "sea", "season",
    "shadow", "shine", "shock", "shower", "sky", "slush", "smoke",
    "snow", "solar", "south", "spring", "storm", "summer", "sun",
    "sunny", "sunset", "swamp", "thunder", "tide", "tornado", "warm",
    "water", "wave", "weather", "west", "wet", "wind", "winter",
}

EMOTIONS_FEELINGS = {
    "abandon", "afraid", "alone", "amused", "anger", "angry", "anxiety",
    "awesome", "awful", "bitter", "blame", "bless", "blush", "boring",
    "brave", "brisk", "calm", "caution", "chaos", "cheap", "chuckle",
    "clumsy", "comfort", "confused", "cool", "crazy", "crisp", "cruel",
    "curious", "cute", "damp", "danger", "daring", "defy", "denial",
    "despair", "dignity", "disagree", "dismiss", "dizzy", "doubt",
    "drama", "dream", "eager", "easy", "effort", "elegant", "elite",
    "emotion", "empty", "endless", "energy", "enjoy", "enrich", "eternal",
    "evil", "exact", "excess", "excite", "exotic", "faith", "fame",
    "famous", "fancy", "fantasy", "fatal", "fatigue", "fault", "favorite",
    "fear", "feel", "fierce", "fine", "firm", "fit", "focus", "fond",
    "fragile", "fresh", "friend", "frown", "fun", "funny", "fury",
    "gentle", "genuine", "ghost", "giggle", "glad", "glare", "gloom",
    "glory", "good", "grace", "great", "grief", "grit", "guilt", "habit",
    "happy", "hard", "harsh", "heavy", "hidden", "high", "hobby", "hole",
    "hollow", "home", "honey", "hope", "horror", "huge", "humble",
    "humor", "hungry", "hurt", "hybrid", "idle", "ignore", "ill",
    "image", "immense", "immune", "impulse", "initial", "innocent",
    "insane", "inspire", "intact", "interest", "involve", "isolate",
    "jealous", "joke", "joy", "keen", "kind", "kiss", "laugh", "lazy",
    "legend", "leisure", "liberty", "like", "limit", "little", "live",
    "lonely", "long", "loud", "love", "loyal", "lucky", "luxury", "mad",
    "magic", "mean", "mercy", "merry", "miracle", "misery", "miss",
    "mistake", "mixed", "moment", "moral", "much", "mutual", "mystery",
    "myth", "naive", "narrow", "nasty", "nature", "near", "negative",
    "neglect", "neutral", "nice", "noble", "noise", "normal", "nothing",
    "novel", "nuclear", "obvious", "odd", "okay", "old", "only", "open",
    "oppose", "option", "ordinary", "original", "other", "outdoor",
    "own", "pain", "panic", "passion", "patient", "pause", "peace",
    "perfect", "permit", "pioneer", "pitch", "pity", "play", "please",
    "pledge", "poem", "point", "popular", "possible", "poverty", "power",
    "practice", "praise", "predict", "prefer", "prepare", "present",
    "pretty", "prevent", "price", "pride", "primary", "print",
    "priority", "private", "problem", "process", "profit", "project",
    "promote", "proof", "property", "prosper", "protect", "proud",
    "provide", "public", "pull", "punch", "purity", "purpose", "push",
    "quality", "question", "quick", "quiet", "quit", "quote", "race",
    "random", "range", "rapid", "rare", "rather", "raw", "ready", "real",
    "reason", "rebel", "recall", "refuse", "regret", "regular", "reject",
    "relax", "release", "relief", "rely", "remain", "remember", "remind",
    "remove", "renew", "repeat", "require", "rescue", "resemble",
    "resist", "response", "result", "retire", "retreat", "return",
    "reveal", "review", "reward", "rhythm", "rich", "right", "rigid",
    "riot", "ripple", "risk", "ritual", "rival", "robust", "romance",
    "rough", "round", "royal", "rude", "rural", "sad", "sadness", "safe",
    "same", "satisfy", "save", "say", "scare", "scheme", "search",
    "secret", "security", "seek", "select", "sense", "series",
    "service", "settle", "setup", "seven", "shallow", "share", "shift",
    "shine", "shiver", "shock", "short", "shove", "shrug", "shuffle",
    "shy", "sick", "sight", "silent", "silly", "similar", "simple",
    "since", "sing", "situate", "six", "size", "skill", "sleep",
    "slender", "slight", "slim", "slow", "small", "smart", "smile",
    "smooth", "snap", "sniff", "social", "soft", "solid", "solve",
    "someone", "song", "soon", "sorry", "sort", "soul", "sound",
    "special", "speed", "spell", "spend", "spirit", "split", "spoil",
    "sponsor", "spray", "spread", "spy", "squeeze", "stable", "stand",
    "start", "state", "stay", "stereo", "still", "sting", "stock",
    "story", "strategy", "strike", "strong", "struggle", "stuff",
    "submit", "success", "such", "sudden", "suffer", "suggest", "summer",
    "super", "supply", "supreme", "sure", "surface", "surprise",
    "surround", "suspect", "sustain", "swallow", "swamp", "swap",
    "swarm", "swear", "sweet", "swift", "swim", "swing", "switch",
    "sword",
}

PEOPLE_ROLES = {
    "account", "actor", "actress", "adult", "agent", "analyst", "artist",
    "athlete", "aunt", "author", "bachelor", "boss", "boy", "bride",
    "brother", "buddy", "buyer", "captain", "chef", "chief", "child",
    "citizen", "clerk", "client", "coach", "congress", "cook", "couple",
    "cousin", "crew", "critic", "dad", "daughter", "dentist", "deputy",
    "doctor", "donor", "driver", "elder", "elite", "employ", "enemy",
    "faculty", "family", "famous", "fan", "father", "female", "friend",
    "genius", "ghost", "giant", "girl", "goddess", "gorilla", "gossip",
    "govern", "group", "guard", "guide", "guru", "gym", "half", "hero",
    "host", "human", "husband", "infant", "inmate", "junior", "judge",
    "kid", "king", "kingdom", "lady", "leader", "legend", "liar",
    "local", "lord", "maid", "major", "mammal", "man", "manage",
    "master", "mate", "mechanic", "member", "mentor", "million",
    "minor", "model", "mom", "monkey", "mother", "myself", "nation",
    "nephew", "nominee", "normal", "nurse", "officer", "orphan", "other",
    "outer", "output", "outside", "own", "owner", "pair", "panel",
    "parent", "party", "patient", "peasant", "people", "person", "pet",
    "pilot", "pioneer", "poet", "police", "position", "power",
    "president", "pride", "primary", "prince", "private", "public",
    "pupil", "puppy", "queen", "race", "rebel", "rich", "rival",
    "robot", "rookie", "royal", "same", "scout", "senior", "sheriff",
    "sibling", "sick", "silly", "simple", "sister", "six", "slave",
    "slim", "smart", "snack", "soccer", "social", "soldier", "someone",
    "son", "soul", "south", "special", "sponsor", "spy", "staff",
    "student", "subject", "super", "supreme", "suspect", "sustain",
    "talent", "tank", "target", "task", "teacher", "team", "tenant",
    "tiger", "toddler", "tourist", "tribe", "twin", "uncle", "unique",
    "unit", "urban", "useless", "usual", "valid", "vast", "vendor",
    "venture", "veteran", "vibrant", "vicious", "victory", "village",
    "vintage", "visa", "visit", "visual", "vital", "vivid", "vocal",
    "voice", "volunteer", "voyage", "wage", "wall", "want", "warfare",
    "warm", "warrior", "waste", "way", "wealth", "weapon", "wear",
    "web", "wedding", "weird", "welcome", "west", "wet", "what",
    "wheat", "wheel", "when", "where", "whip", "whisper", "wide",
    "width", "wife", "wild", "will", "win", "window", "wine", "wing",
    "wink", "winner", "winter", "wire", "wisdom", "wise", "wish",
    "witness", "wolf", "woman", "wonder", "word", "work", "world",
    "worry", "worth", "wrap", "wreck", "wrestle", "wrist", "write",
    "wrong", "yard", "year", "yellow", "you", "young", "youth", "zebra",
    "zero", "zone", "zoo",
}

FOOD_DRINK = {
    "apple", "avocado", "bacon", "banana", "bean", "beef", "bread",
    "broccoli", "burger", "butter", "cabbage", "cake", "candy", "celery",
    "cereal", "cheese", "cherry", "chicken", "cinnamon", "coconut",
    "coffee", "corn", "cotton", "cream", "diet", "dinner", "egg",
    "fat", "feed", "flavor", "food", "fruit", "garlic", "ginger",
    "grain", "grape", "grocery", "harvest", "honey", "hungry", "juice",
    "ketchup", "kiwi", "lemon", "lunch", "mango", "meal", "meat",
    "milk", "muffin", "mushroom", "noodle", "nut", "oat", "oil",
    "olive", "onion", "orange", "oyster", "peanut", "pear", "pepper",
    "picnic", "pizza", "potato", "pudding", "pumpkin", "recipe", "rice",
    "roast", "salad", "salmon", "salt", "sample", "sauce", "sausage",
    "seed", "shrimp", "slice", "snack", "soap", "soda", "soup", "spice",
    "steak", "sugar", "supply", "sweet", "syrup", "taste", "toast",
    "tobacco", "tomato", "treat", "tuna", "turkey", "vanilla", "walnut",
    "water", "wheat", "wine",
}

PLACES_GEOGRAPHY = {
    "airport", "alley", "arena", "arctic", "area", "bar", "base",
    "beach", "border", "cabin", "camp", "canal", "canyon", "capital",
    "casino", "castle", "cave", "ceiling", "center", "city", "civil",
    "cliff", "clinic", "coast", "country", "creek", "desert", "domain",
    "door", "earth", "east", "edge", "entire", "entry", "estate",
    "exit", "farm", "field", "floor", "forest", "forum", "front",
    "galaxy", "gap", "garage", "garden", "gate", "globe", "gym",
    "harbor", "hill", "hole", "hollow", "home", "hospital", "hotel",
    "hub", "indoor", "island", "jungle", "kingdom", "lab", "lake",
    "lawn", "library", "local", "lounge", "mansion", "margin", "marine",
    "market", "meadow", "middle", "mountain", "museum", "nation",
    "nature", "near", "nest", "network", "next", "north", "oak",
    "ocean", "office", "open", "orchard", "outdoor", "outer",
    "outside", "ozone", "palace", "palm", "park", "path", "planet",
    "platform", "plaza", "pole", "pond", "pool", "position", "prison",
    "property", "public", "pyramid", "race", "rail", "ranch", "range",
    "region", "ridge", "ring", "river", "road", "roof", "room",
    "route", "royal", "rural", "runway", "salon", "sand", "scene",
    "school", "sea", "section", "settle", "shed", "shop", "side",
    "sight", "site", "slot", "south", "space", "spot", "square",
    "stable", "stadium", "stage", "stairs", "state", "station",
    "store", "street", "suburb", "surface", "swamp", "temple",
    "tent", "there", "tide", "top", "total", "tourist", "toward",
    "tower", "town", "track", "trail", "tree", "tunnel", "universe",
    "upper", "urban", "valley", "vault", "venue", "village",
    "volcano", "wall", "ward", "way", "web", "west", "where", "wide",
    "window", "winter", "world", "yard", "zone", "zoo",
}

POSITIVE_QUALITY = {
    "ability", "achieve", "awesome", "balance", "beauty", "benefit",
    "best", "better", "bless", "brave", "bright", "calm", "capable",
    "certain", "champion", "change", "clean", "clever", "comfort",
    "correct", "creative", "cute", "daring", "dignity", "eager",
    "easy", "educate", "effort", "elegant", "elite", "embrace",
    "empower", "enable", "energy", "enjoy", "enrich", "ensure", "equal",
    "eternal", "ethics", "exact", "example", "excite", "faith", "fame",
    "famous", "fancy", "favorite", "fine", "first", "fit", "focus",
    "fresh", "friend", "fun", "funny", "genius", "gentle", "genuine",
    "gift", "glad", "glory", "gold", "good", "grace", "grant", "great",
    "grit", "guide", "happy", "health", "heart", "hero", "high",
    "hobby", "home", "honest", "honey", "honor", "hope", "humble",
    "humor", "immune", "improve", "include", "initial", "innocent",
    "inspire", "intact", "interest", "jewel", "joy", "just", "keen",
    "kind", "kiss", "know", "laugh", "leader", "learn", "legend",
    "leisure", "liberty", "life", "light", "like", "live", "love",
    "loyal", "lucky", "luxury", "magic", "major", "master", "merit",
    "merry", "miracle", "moral", "mutual", "nature", "near", "nice",
    "noble", "normal", "novel", "okay", "open", "option", "original",
    "own", "palace", "partner", "patient", "peace", "perfect", "permit",
    "pioneer", "please", "pledge", "point", "popular", "possible",
    "power", "practice", "praise", "prefer", "prepare", "present",
    "pretty", "pride", "primary", "priority", "prize", "profit",
    "promote", "proof", "prosper", "protect", "proud", "provide",
    "public", "purity", "purpose", "quality", "quick", "ready", "real",
    "reason", "recipe", "regular", "relax", "release", "relief", "rely",
    "remember", "renew", "rescue", "resource", "response", "result",
    "reveal", "reward", "rich", "right", "robust", "romance", "royal",
    "safe", "satisfy", "save", "search", "secret", "security", "seek",
    "select", "sense", "service", "settle", "share", "shelter", "shine",
    "simple", "sing", "skill", "smart", "smile", "smooth", "social",
    "solid", "solve", "soul", "sound", "special", "spirit", "stable",
    "stand", "start", "stay", "still", "strong", "stuff", "style",
    "success", "summer", "sun", "sunny", "super", "supply", "supreme",
    "sure", "surprise", "sustain", "sweet", "swift", "talent", "taste",
    "team", "thrive", "together", "top", "total", "travel", "treat",
    "trend", "trophy", "true", "truly", "trust", "truth", "unique",
    "unit", "universe", "update", "upgrade", "uphold", "useful", "valid",
    "value", "vast", "venture", "veteran", "vibrant", "victory",
    "vintage", "vital", "vivid", "vocal", "voice", "voyage", "warm",
    "way", "wealth", "welcome", "wide", "will", "win", "window",
    "wine", "wing", "winner", "winter", "wire", "wisdom", "wise",
    "wish", "wonder", "wood", "wool", "word", "work", "world", "worth",
    "write", "year", "young", "youth",
}

NEGATIVE_QUALITY = {
    "abandon", "absent", "absurd", "abuse", "accident", "accuse",
    "acid", "afraid", "alone", "anger", "angry", "anxiety", "argue",
    "arrest", "arrogant", "assault", "attack", "awful", "awkward",
    "betray", "bitter", "blade", "blame", "bleak", "blind", "blood",
    "bomb", "boring", "broken", "burden", "busy", "cage", "cancel",
    "caught", "caution", "chaos", "cheap", "chronic", "clumsy",
    "collapse", "conflict", "confuse", "corrupt", "crack", "crash",
    "crazy", "crime", "crisp", "critic", "crowd", "cruel", "crumble",
    "crunch", "crush", "cry", "damage", "damp", "danger", "dark",
    "debris", "decade", "decline", "decrease", "defeat", "define",
    "defy", "delay", "demand", "demise", "denial", "deny", "depart",
    "depend", "desert", "despair", "destroy", "detail", "detect",
    "develop", "device", "devote", "differ", "digital", "dilemma",
    "dirt", "disagree", "discover", "disease", "dish", "dismiss",
    "disorder", "display", "distance", "divert", "divide", "divorce",
    "dizzy", "doom", "doubt", "draft", "drastic", "drift", "drop",
    "dumb", "during", "dust", "duty", "dwarf", "dynamic", "edge",
    "effort", "either", "else", "emotion", "empty", "end", "endless",
    "endorse", "enemy", "enforce", "engage", "enough", "enroll",
    "entire", "entry", "envelope", "episode", "equal", "equip", "era",
    "erase", "erode", "erosion", "error", "erupt", "escape", "essay",
    "essence", "estate", "eternal", "evidence", "evil", "evoke",
    "evolve", "exact", "example", "excess", "exchange", "exclude",
    "excuse", "execute", "exercise", "exhaust", "exhibit", "exile",
    "exist", "exit", "exotic", "expand", "expect", "expire", "explain",
    "expose", "express", "extend", "extra", "fabric", "fade", "faint",
    "fall", "false", "fatal", "fatigue", "fault", "fever", "few",
    "fiction", "figure", "final", "fire", "fiscal", "flat", "flee",
    "flight", "flip", "float", "flock", "flood", "floor", "flush",
    "fog", "fold", "follow", "fool", "force", "forget", "fortune",
    "fossil", "found", "fragile", "frequent", "friction", "fringe",
    "frost", "frozen", "frown", "fury", "garbage", "gasp", "ghost",
    "glare", "gloom", "gossip", "grief", "grit", "guilt", "gun",
    "habit", "hard", "harsh", "hate", "hazard", "heavy", "hidden",
    "horror", "hostile", "humble", "hungry", "hurdle", "hurry", "hurt",
    "hybrid", "idle", "ignore", "ill", "illegal", "illness", "impose",
    "impulse", "incident", "include", "income", "increase", "index",
    "indicate", "indoor", "industry", "infant", "inflict", "inform",
    "inhale", "inherit", "initial", "inject", "injury", "inmate",
    "inner", "input", "inquiry", "insane", "insect", "inside",
    "install", "intact", "into", "invest", "invite", "involve",
    "isolate", "issue", "jealous", "junk", "just", "keen", "kick",
    "labor", "later", "law", "lawsuit", "lazy", "liar", "limit",
    "liquid", "load", "lock", "lonely", "long", "loop", "loss", "loud",
    "mad", "mandate", "margin", "mass", "matter", "maximum", "maze",
    "mean", "measure", "mess", "midnight", "million", "mimic", "mind",
    "minimum", "minor", "minute", "misery", "miss", "mistake", "mix",
    "mixed", "mixture", "monitor", "much", "must", "mutual", "mystery",
    "myth", "naive", "name", "narrow", "nasty", "need", "negative",
    "neglect", "neither", "nervous", "never", "noise", "nothing",
    "notice", "now", "nuclear", "number", "object", "oblige", "obscure",
    "observe", "obtain", "obvious", "occur", "odd", "off", "often",
    "old", "only", "oppose", "ordinary", "other", "outer", "output",
    "outside", "oval", "over", "own", "oxygen", "ozone", "pact",
    "pain", "panic", "pass", "patrol", "penalty", "people", "pepper",
    "permit", "person", "physical", "piece", "pig", "pink", "pipe",
    "pistol", "pitch", "place", "planet", "plastic", "plate", "play",
    "please", "pluck", "plug", "plunge", "poem", "poet", "point",
    "polar", "pole", "police", "pond", "portion", "position",
    "possible", "post", "poverty", "predict", "price", "prison",
    "private", "problem", "process", "produce", "program", "project",
    "proof", "property", "protect", "provide", "public", "pull",
    "pulp", "punch", "pupil", "purchase", "purse", "push", "put",
    "puzzle", "quarter", "question", "quick", "quit", "quiz", "quote",
    "rack", "radar", "radio", "rail", "rain", "raise", "rally", "ramp",
    "ranch", "random", "range", "rapid", "rare", "rate", "rather",
    "raw", "real", "reason", "rebel", "rebuild", "recall", "receive",
    "record", "recycle", "reduce", "reflect", "reform", "refuse",
    "region", "regret", "regular", "reject", "release", "relief",
    "rely", "remain", "remember", "remind", "remove", "render", "renew",
    "rent", "reopen", "repair", "repeat", "replace", "report",
    "require", "rescue", "resemble", "resist", "resource", "response",
    "result", "retire", "retreat", "return", "reunion", "reveal",
    "review", "reward", "rhythm", "rib", "ribbon", "rice", "rich",
    "ride", "ridge", "rifle", "right", "rigid", "ring", "riot",
    "ripple", "risk", "ritual", "rival", "river", "road", "roast",
    "robot", "robust", "rocket", "romance", "roof", "rookie", "room",
    "rose", "rotate", "rough", "round", "route", "royal", "rubber",
    "rude", "rug", "rule", "run", "runway", "rural", "sad", "saddle",
    "sadness", "safe", "sail", "salad", "salmon", "salon", "salute",
    "same", "sample", "sand", "satisfy", "satoshi", "sauce", "sausage",
    "save", "say", "scale", "scan", "scare", "scatter", "scene",
    "scheme", "school", "science",
}

ACTION_VERB = {
    "abandon", "able", "absorb", "access", "achieve", "acquire", "across",
    "act", "action", "actual", "adapt", "add", "adjust", "admit",
    "advance", "afford", "agree", "aim", "allow", "alter", "announce",
    "appear", "approve", "argue", "arrange", "arrest", "arrive", "ask",
    "assist", "assume", "attend", "attract", "auction", "avoid", "awake",
    "balance", "barely", "battle", "become", "begin", "behave", "believe",
    "betray", "bid", "bind", "blast", "bless", "board", "boil", "boost",
    "borrow", "bounce", "bring", "brush", "bubble", "build", "burst",
    "buy", "call", "cancel", "capture", "carry", "catch", "caught",
    "cause", "celebrate", "change", "charge", "chase", "chat", "check",
    "choose", "chuckle", "churn", "circle", "claim", "clap", "clarify",
    "clean", "click", "climb", "clip", "close", "clutch", "collect",
    "combine", "come", "conduct", "confirm", "connect", "consider",
    "control", "convince", "cook", "copy", "correct", "cover", "crack",
    "cram", "crash", "crawl", "create", "crop", "cross", "crouch",
    "crumble", "crunch", "crush", "cry", "cut", "cycle",
    "dance", "deal", "debate", "decide", "decline", "decorate",
    "decrease", "define", "defy", "delay", "deliver", "demand", "deny",
    "depart", "depend", "deposit", "derive", "describe", "design",
    "destroy", "detect", "develop", "devote", "differ", "direct",
    "disagree", "discover", "dismiss", "display", "divert", "divide",
    "donate", "double", "draft", "draw", "dream", "dress", "drift",
    "drink", "drive", "drop", "earn", "echo", "edit", "educate",
    "embark", "embody", "embrace", "emerge", "employ", "empower",
    "enable", "enact", "endorse", "enforce", "engage", "enhance",
    "enjoy", "enlist", "enrich", "enroll", "ensure", "enter", "equip",
    "erase", "erode", "erupt", "escape", "evolve", "exchange", "excite",
    "exclude", "excuse", "execute", "exercise", "exhibit", "exist",
    "expand", "expect", "expire", "explain", "expose", "express",
    "extend", "face", "fade", "fall", "fancy", "fashion", "feed",
    "feel", "fetch", "figure", "file", "film", "filter", "find",
    "finish", "fire", "fit", "fix", "flee", "flight", "flip", "float",
    "flock", "flush", "fly", "focus", "fold", "follow", "force",
    "forget", "forward", "foster", "found", "gain", "gasp", "gather",
    "gaze", "gesture", "giggle", "give", "glance", "glare", "glide",
    "glimpse", "glow", "govern", "grab", "grant", "gravity", "grip",
    "grow", "grunt", "guard", "guess", "guide",
    "have", "head", "help", "hide", "hint", "hire", "hold", "hope",
    "host", "hover", "hunt", "hurdle", "hurry", "identify", "ignore",
    "illustrate", "imitate", "impose", "improve", "include", "increase",
    "indicate", "inflict", "inform", "inhale", "inherit", "inject",
    "inspire", "install", "invest", "invite", "involve", "isolate",
    "join", "journey", "judge", "jump", "keep", "kick", "knock", "know",
    "labor", "laugh", "launch", "learn", "leave", "lend", "lift",
    "limit", "link", "list", "live", "load", "locate", "lock",
    "make", "manage", "mandate", "march", "market", "match", "mean",
    "measure", "melt", "mention", "merge", "mimic", "mind", "miss",
    "mix", "model", "modify", "monitor", "move", "multiply",
    "name", "need", "neglect", "note", "notice", "obey", "object",
    "oblige", "observe", "obtain", "occur", "offer", "omit", "open",
    "oppose", "orbit", "order", "orient", "own",
    "pass", "patrol", "pause", "pave", "permit", "phrase", "place",
    "play", "please", "pledge", "pluck", "plug", "plunge", "point",
    "post", "power", "practice", "praise", "predict", "prefer",
    "prepare", "present", "prevent", "print", "process", "produce",
    "profit", "program", "project", "promote", "protect", "provide",
    "publish", "pull", "punch", "purchase", "push", "put",
    "question", "quit", "quote",
    "race", "raise", "rally", "range", "rate", "raw", "ready",
    "reason", "rebel", "rebuild", "recall", "receive", "record",
    "recycle", "reduce", "reflect", "reform", "refuse", "reject",
    "relax", "release", "rely", "remain", "remember", "remind",
    "remove", "render", "renew", "rent", "reopen", "repair", "repeat",
    "replace", "report", "require", "rescue", "resemble", "resist",
    "respond", "result", "retire", "retreat", "return", "reveal",
    "review", "reward", "ride", "risk", "rival", "roast", "rotate",
    "rule", "run", "rush",
    "sail", "salute", "sample", "satisfy", "save", "say", "scan",
    "scare", "scatter", "schedule", "scout", "scrap", "scrub", "search",
    "seat", "seek", "select", "sell", "sense", "sentence", "series",
    "serve", "service", "session", "settle", "setup", "share", "shed",
    "shift", "shine", "shiver", "shock", "shoot", "shop", "shove",
    "shrug", "shuffle", "sign", "sing", "situate", "skate", "sketch",
    "ski", "slam", "sleep", "slice", "slide", "slim", "slow", "smile",
    "smoke", "snap", "sniff", "solve", "sort", "sound", "spawn",
    "speak", "spell", "spend", "spin", "split", "spoil", "sponsor",
    "spot", "spray", "spread", "spy", "squeeze", "stamp", "stand",
    "start", "state", "stay", "step", "stick", "sting", "stock",
    "strike", "struggle", "stumble", "submit", "suggest", "supply",
    "surround", "survey", "suspect", "sustain", "swallow", "swap",
    "swarm", "swear", "swim", "swing", "switch",
    "tackle", "talk", "tank", "target", "taste", "teach", "tell",
    "tend", "test", "thank", "think", "thought", "throw", "tilt",
    "tip", "toast", "toss", "total", "touch", "track", "trade",
    "train", "transfer", "trap", "travel", "treat", "trend", "trick",
    "trigger", "trim", "trip", "trouble", "trust", "try", "tumble",
    "turn", "twist", "type",
    "uncover", "undo", "unfold", "unveil", "update", "upgrade",
    "uphold", "urge", "use",
    "vanish", "verify", "view", "visit", "voice", "vote",
    "wait", "walk", "want", "warn", "wash", "waste", "watch", "wave",
    "wear", "welcome", "will", "win", "wish", "witness", "wonder",
    "work", "worry", "wrap", "wreck", "wrestle", "write",
}

DESCRIPTION_QUALITY = {
    "about", "above", "abstract", "absurd", "acoustic", "actual",
    "aerobic", "almost", "alone", "already", "also", "always", "amateur",
    "amazing", "among", "amount", "ancient", "angry", "annual",
    "another", "any", "apart", "aware", "awkward",
    "barely", "basic", "below", "best", "better", "between", "beyond",
    "black", "bleak", "blind", "blue", "boring", "brave", "brief",
    "bright", "brisk", "broad", "broken", "brown", "brutal", "bulk",
    "busy",
    "capable", "capital", "casual", "caught", "central", "certain",
    "cheap", "chief", "chronic", "civil", "clean", "clear", "clever",
    "close", "cold", "common", "company", "complete", "congress",
    "consider", "control", "convince", "cool", "correct", "crazy",
    "crisp", "crucial", "cruel", "curious", "current", "custom", "cute",
    "damp", "daring", "dark", "deadly", "dear", "decent", "deep",
    "digital", "direct", "dirty", "dizzy", "double", "drastic", "dry",
    "dumb", "during", "dutch", "dynamic",
    "eager", "early", "easily", "easy", "echo", "economy", "edge",
    "eight", "either", "electric", "elegant", "elite", "else", "empty",
    "endless", "enough", "entire", "equal", "era", "eternal", "even",
    "evil", "exact", "exotic", "express", "extra", "extreme",
    "fabric", "faculty", "faint", "fair", "false", "famous", "fancy",
    "fatal", "favorite", "federal", "female", "few", "final", "fine",
    "firm", "first", "fiscal", "flat", "foreign", "forward", "fossil",
    "fragile", "free", "frequent", "fresh", "frozen", "fuel", "full",
    "funny", "future",
    "general", "generic", "genius", "gentle", "genuine", "giant",
    "glad", "global", "good", "great", "green", "grit", "gross",
    "guilty",
    "half", "happy", "hard", "harsh", "hazard", "healthy", "heart",
    "heavy", "hidden", "high", "hollow", "honest", "horizontal",
    "horrible", "hospital", "hostile", "hot", "hour", "huge", "humble",
    "hundred", "hungry", "hybrid",
    "idle", "ill", "illegal", "immense", "immune", "important",
    "include", "indoor", "infant", "initial", "inner", "innocent",
    "insane", "inside", "intact", "interest",
    "junior", "just",
    "keen", "key", "kind",
    "large", "later", "latin", "lazy", "left", "legal", "leisure",
    "level", "liar", "light", "like", "little", "live", "local",
    "lonely", "long", "loud", "loyal", "lucky", "lunar", "luxury",
    "mad", "magic", "main", "major", "manual", "marine", "mass",
    "material", "math", "matter", "maximum", "mean", "merry", "middle",
    "midnight", "million", "minimum", "minor", "minute", "mixed",
    "mobile", "modern", "moment", "month", "moral", "more", "morning",
    "much", "multiple", "must", "mutual",
    "naive", "narrow", "nasty", "near", "negative", "neither", "neutral",
    "never", "new", "next", "nice", "noble", "noise", "nominee",
    "normal", "north", "notable", "nothing", "novel", "now", "nuclear",
    "number",
    "obvious", "odd", "off", "often", "okay", "old", "olympic", "once",
    "one", "online", "only", "open", "opinion", "oppose", "option",
    "ordinary", "orient", "original", "other", "outdoor", "outer",
    "outside", "over", "own",
    "patient", "perfect", "permanent", "physical", "pink", "pioneer",
    "pitch", "plastic", "polar", "popular", "possible", "potential",
    "poverty", "power", "present", "pretty", "previous", "primary",
    "priority", "private", "public", "pull", "pure", "purpose",
    "quality", "quantum", "quarter", "question", "quick", "quiet",
    "quiz",
    "random", "range", "rapid", "rare", "rather", "raw", "ready",
    "real", "reason", "rebel", "regular", "relief", "rigid", "risk",
    "ritual", "rival", "robust", "romance", "rough", "round", "royal",
    "rude", "rural",
    "sad", "sadness", "safe", "same", "satisfy", "second", "secret",
    "security", "senior", "sense", "series", "session", "setup",
    "seven", "shallow", "sharp", "shift", "short", "shy", "sick",
    "sight", "silent", "silly", "silver", "similar", "simple", "since",
    "situate", "six", "size", "slender", "slight", "slim", "slow",
    "small", "smart", "smooth", "social", "soft", "solar", "solid",
    "soon", "sorry", "soul", "south", "spatial", "special", "speed",
    "stable", "standard", "state", "stay", "stereo", "still", "stock",
    "stone", "story", "strategy", "street", "strike", "strong",
    "struggle", "student", "stuff", "style", "subject", "submit",
    "subtle", "success", "such", "sudden", "sugar", "suit", "summer",
    "sun", "sunny", "sunset", "super", "supply", "supreme", "sure",
    "surface", "surprise", "suspect", "sustain", "sweet", "swift",
    "symbol", "symptom", "system",
    "talent", "taste", "team", "ten", "tenant", "tennis", "term",
    "test", "text", "that", "theme", "then", "theory", "there", "they",
    "thing", "this", "thought", "three", "thrive", "ticket", "tide",
    "tiger", "tilt", "timber", "time", "tiny", "tired", "tissue",
    "title", "today", "toddler", "together", "toilet", "token",
    "tomorrow", "tone", "tonight", "top", "topic", "topple", "total",
    "toward", "town", "track", "trade", "traffic", "tragic", "train",
    "transfer", "trap", "trash", "travel", "treat", "trend", "trial",
    "tribe", "trick", "trigger", "trim", "trip", "trophy", "trouble",
    "truck", "true", "truly", "trumpet", "trust", "truth", "try",
    "tube", "tuition", "tumble", "tunnel", "turkey", "turn", "twelve",
    "twenty", "twice", "twin", "twist", "two", "type", "typical",
    "ugly", "umbrella", "unable", "unaware", "uncle", "under", "undo",
    "unfair", "unfold", "unhappy", "uniform", "unique", "unit",
    "universe", "unknown", "unlock", "until", "unusual", "unveil",
    "update", "upgrade", "uphold", "upon", "upper", "upset", "urban",
    "usage", "use", "used", "useful", "useless", "usual", "utility",
    "vacant", "vacuum", "vague", "valid", "valley", "valve", "van",
    "vanish", "vapor", "various", "vast", "vault", "vehicle", "velvet",
    "vendor", "venture", "venue", "verb", "verify", "version", "very",
    "vessel", "veteran", "viable", "vibrant", "vicious", "victory",
    "video", "view", "village", "vintage", "violin", "virtual", "virus",
    "visa", "visit", "visual", "vital", "vivid", "vocal", "voice",
    "void", "volcano", "volume", "vote", "voyage",
    "wage", "wagon", "wait", "walk", "wall", "walnut", "want",
    "warfare", "warm", "warrior", "wash", "waste", "water", "wave",
    "way", "wealth", "weapon", "wear", "weather", "web", "wedding",
    "weekend", "weird", "welcome", "west", "wet", "what", "wheat",
    "wheel", "when", "where", "whip", "whisper", "wide", "width",
    "wife", "wild", "will", "win", "window", "wine", "wing", "wink",
    "winner", "winter", "wire", "wisdom", "wise", "wish", "witness",
    "wolf", "woman", "wonder", "wood", "wool", "word", "work", "world",
    "worry", "worth", "wrap", "wreck", "wrestle", "wrist", "write",
    "wrong", "yard", "year", "yellow", "you", "young", "youth",
    "zebra", "zero", "zone", "zoo",
}

PHYSICAL_HOLDABLE = {
    "anchor", "apple", "arrow", "axe", "badge", "bag", "ball", "banana",
    "bar", "barrel", "basket", "bell", "belt", "blade", "blanket",
    "bomb", "bone", "book", "bottle", "box", "brick", "broom", "brush",
    "bucket", "bullet", "cable", "cage", "cake", "camera", "can",
    "candle", "cannon", "canvas", "card", "carpet", "case", "chain",
    "chair", "chalk", "cigar", "clay", "clip", "clock", "cloth", "club",
    "clutch", "code", "coil", "coin", "comb", "compass", "cookie",
    "coral", "core", "corn", "couch", "cradle", "crane", "crystal",
    "cube", "cup", "cupboard", "curtain", "cushion", "desk", "device",
    "diagram", "dial", "diamond", "diary", "dice", "dish", "doll",
    "dose", "dress", "drill", "drum", "dust", "egg", "envelope",
    "fabric", "fan", "file", "film", "filter", "flag", "flame",
    "flash", "flip", "float", "foam", "foil", "fold", "food", "fork",
    "frame", "fruit", "fuel", "furniture", "gadget", "gas", "gauge",
    "gift", "glass", "globe", "glove", "glue", "gold", "grain",
    "grape", "grid", "guitar", "gun", "half", "hammer", "hat", "helmet",
    "horn", "ice", "image", "inch", "iron", "item", "ivory", "jacket",
    "jar", "jeans", "jewel", "junk", "key", "kit", "kite", "knife",
    "label", "ladder", "lamp", "laptop", "leaf", "lemon", "lens",
    "letter", "license", "light", "link", "list", "load", "lobster",
    "lock", "luggage", "lumber", "machine", "magnet", "mail", "manual",
    "marble", "mask", "match", "material", "matrix", "maze", "medal",
    "menu", "mesh", "message", "metal", "method", "milk", "mirror",
    "mobile", "model", "monitor", "motor", "muffin", "mushroom", "net",
    "network", "note", "nut", "object", "oil", "olive", "onion",
    "orange", "organ", "oven", "oxygen", "package", "paddle", "page",
    "pair", "panel", "paper", "patch", "pattern", "payment", "pen",
    "pencil", "pepper", "phone", "photo", "piano", "picture", "piece",
    "pig", "pill", "pillow", "pin", "pipe", "pistol", "pizza", "plate",
    "plastic", "plug", "plunge", "poem", "pole", "pottery", "powder",
    "print", "prize", "proof", "pudding", "pulp", "pump", "punch",
    "purse", "puzzle", "rack", "radar", "radio", "rail", "ramp",
    "razor", "recipe", "record", "ribbon", "rice", "rifle", "ring",
    "road", "robot", "rocket", "rope", "rubber", "rug", "saddle",
    "sail", "salt", "sample", "sand", "sauce", "sausage", "scale",
    "scissors", "screen", "script", "seat", "shell", "shield", "ship",
    "shoe", "silk", "silver", "skate", "sketch", "ski", "skirt", "slab",
    "slice", "slide", "slot", "snack", "soap", "sock", "soda", "spice",
    "spike", "spoon", "spray", "staff", "stamp", "steel", "stereo",
    "stick", "stone", "stool", "stove", "stuff", "suit", "supply",
    "surface", "sword", "symbol", "syrup", "table", "tackle", "tag",
    "tail", "tank", "tape", "target", "tattoo", "tent", "text",
    "ticket", "timber", "title", "toast", "tobacco", "token", "tool",
    "top", "torch", "toy", "tray", "treat", "trigger", "trim",
    "trophy", "truck", "trumpet", "tube", "umbrella", "uniform",
    "vacuum", "valve", "van", "vapor", "vault", "vehicle", "velvet",
    "vessel", "video", "violin", "virus", "visa", "volume", "wagon",
    "wallet", "wall", "weapon", "web", "wheel", "whip", "window",
    "wine", "wire", "wood", "wool", "wrap", "wreck",
}

# ============================================================
# BUILD CATEGORY MAP
# ============================================================

categories = {}
for word in words:
    tags = []
    if word in ANIMALS: tags.append("animal")
    if word in NATURE_PLANTS: tags.append("nature_plant")
    if word in BODY_PARTS: tags.append("body_part")
    if word in TOOLS_OBJECTS: tags.append("tool_object")
    if word in SPACE_ASTRONOMY: tags.append("space")
    if word in WEATHER_ELEMENTS: tags.append("weather_element")
    if word in EMOTIONS_FEELINGS: tags.append("emotion_feeling")
    if word in PEOPLE_ROLES: tags.append("person_role")
    if word in FOOD_DRINK: tags.append("food_drink")
    if word in PLACES_GEOGRAPHY: tags.append("place")
    if word in POSITIVE_QUALITY: tags.append("positive")
    if word in NEGATIVE_QUALITY: tags.append("negative")
    if word in PHYSICAL_HOLDABLE: tags.append("holdable")
    if word in ACTION_VERB: tags.append("action")
    if word in DESCRIPTION_QUALITY: tags.append("descriptor")
    if not tags:
        tags.append("abstract")
    categories[word] = tags

# Stats
from collections import Counter
tag_counts = Counter()
for tags in categories.values():
    for t in tags:
        tag_counts[t] += 1

print(f"Categorized {len(categories)} words")
print(f"\nTag distribution:")
for tag, count in tag_counts.most_common():
    print(f"  {tag}: {count} ({count/len(words)*100:.1f}%)")

uncategorized = [w for w, t in categories.items() if t == ["abstract"]]
print(f"\nUncategorized (abstract): {len(uncategorized)}")
if uncategorized[:20]:
    print(f"  Examples: {', '.join(uncategorized[:20])}")

# Save
with open("bip39_categories.json", "w") as f:
    json.dump(categories, f, indent=2, sort_keys=True)

print(f"\nSaved to bip39_categories.json")
